import 'package:freezed_annotation/freezed_annotation.dart';

part 'message.freezed.dart';
part 'message.g.dart';

/// The kind of content carried by a [Message].
enum MessageType {
  /// Plain text (markdown supported).
  text,

  /// A fenced code block with optional language tag.
  code,

  /// A git-style unified diff.
  diff,

  /// A prompt that requires user action (e.g. Allow / Deny).
  action,

  /// A system notification (connected, disconnected, etc.).
  system,

  /// A structured tool use event from Claude Code hooks.
  toolUse,

  /// A multi-choice question from Claude (AskUserQuestion tool).
  askQuestion,

  /// Claude's text response extracted from transcript (via Stop hook).
  claudeResponse,

  /// Claude's thinking/processing status indicator.
  thinking,

  /// A background agent lifecycle event (started/stopped).
  subagentEvent,

  /// Incoming file offer from computer.
  fileOffer,

  /// Active file transfer progress.
  fileProgress,

  /// File transfer completed.
  fileComplete,

  /// List of resumable sessions from bridge.
  sessionList,
}

/// Who sent the message.
enum MessageSender {
  /// Claude Code on the remote computer.
  claude,

  /// The local user on the phone.
  user,

  /// Generated by the app itself.
  system,
}

/// A single chat message.
@freezed
class Message with _$Message {
  const factory Message({
    required String id,
    required MessageType type,
    required MessageSender sender,
    required String content,
    required DateTime timestamp,

    /// Programming language for [MessageType.code] blocks.
    String? language,

    /// Parsed diff lines for [MessageType.diff] messages.
    List<DiffLine>? diffLines,

    /// Pending action for [MessageType.action] messages.
    PendingAction? action,

    /// Tool name for [MessageType.toolUse] messages (e.g. "Edit", "Bash").
    String? toolName,

    /// Tool execution status: "pending", "success", or "error".
    String? toolStatus,

    /// Tool input data (file path, command, etc.).
    Map<String, dynamic>? toolInput,

    /// Tool output/result text.
    String? toolResult,

    /// Error message if tool execution failed.
    String? toolError,

    /// Questions for [MessageType.askQuestion] messages.
    List<Map<String, dynamic>>? questions,

    /// Subagent ID for [MessageType.subagentEvent] messages.
    String? agentId,

    /// Subagent type (e.g. "Explore", "Bash") for [MessageType.subagentEvent].
    String? agentType,

    /// Subagent status: "started" or "stopped".
    String? agentStatus,

    /// Transfer ID for file transfer messages.
    String? transferId,

    /// File name for file transfer messages.
    String? fileName,

    /// MIME type for file transfer messages.
    String? mimeType,

    /// File size in bytes for file transfer messages.
    int? fileSize,

    /// Transfer progress (0.0 - 1.0) for [MessageType.fileProgress].
    double? transferProgress,

    /// Local file path after download for [MessageType.fileComplete].
    String? localFilePath,

    /// Whether the transfer completed successfully.
    bool? transferSuccess,
  }) = _Message;

  factory Message.fromJson(Map<String, dynamic> json) =>
      _$MessageFromJson(json);
}

/// The type of a single line inside a unified diff.
enum DiffType {
  /// An added line (green).
  add,

  /// A removed line (red).
  remove,

  /// An unchanged context line (gray).
  context,
}

/// A single line in a unified diff view.
@freezed
class DiffLine with _$DiffLine {
  const factory DiffLine({
    required String content,
    required DiffType type,
    required int lineNumber,
  }) = _DiffLine;

  factory DiffLine.fromJson(Map<String, dynamic> json) =>
      _$DiffLineFromJson(json);
}

/// An action that the user must respond to (e.g. "Allow file edit?").
@freezed
class PendingAction with _$PendingAction {
  const factory PendingAction({
    required String id,
    required String prompt,

    /// e.g. ["Allow", "Deny"] or ["Yes", "No"].
    required List<String> options,

    /// Whether the user has already responded.
    @Default(false) bool responded,

    /// The chosen response value, if any.
    String? response,
  }) = _PendingAction;

  factory PendingAction.fromJson(Map<String, dynamic> json) =>
      _$PendingActionFromJson(json);
}
